name: 이미지 빌드 & 푸쉬
on:
  workflow_call:
    inputs:
      java-module-name:
        required: true
        type: string
      ecr-repository-name:
        required: true
        type: string
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      spring-profile:
        required: true
        type: string
      local:
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ASSUME_ROLE_ARN:
        required: true
      AWS_ECR_REGISTRY_URL:
        required: true
      AWS_REGION:
        required: true

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    name: 이미지 빌드하기

    permissions:
      id-token: write
      contents: read

    steps:
      - name: GitHub 에서 레포 받아오기
        uses: actions/checkout@v3

      - name: AWS 인증정보 준비하기
        if: inputs.local == false
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR 로그인하기
        if: inputs.local == false
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: JDK17 준비하기
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 준비하기
        uses: gradle/gradle-build-action@v2

      - name: 이미지 빌드하고 푸쉬하기
        id: build-image
        env:
          IMAGE_TAG: ${{ needs.prepare.outputs.imageTag }}
          ECR_REGISTRY_PREFIX: '${{ secrets.AWS_ECR_REGISTRY_URL }}/'
        run: |
          /bin/bash build.sh \
            ${{ inputs.java-module-name }} \
            ${{ env.ECR_REGISTRY_PREFIX }}${{ inputs.ecr-repository-name }} \
            ${{ inputs.image-tag }} \
            ${{ inputs.spring-profile }}